name: clang-format
permissions:
  contents: read

on:
  workflow_call:
    inputs:
      clang-version:
        description: "The version of Clang/LLVM to use"
        type: string
        required: false
        default: "18"
  pull_request:
    types: [ opened, synchronize, reopened, closed ]

jobs:
  format:
    runs-on: ubuntu-24.04

    env:
      CLANG_VERSION: ${{ inputs.clang-version || '18' }}

    steps:
      - name: Checkout
        uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2
        with:
          persist-credentials: false

      - name: Install clang-format
        run: |
          # Disable man-db (massive speed-up!)
          sudo apt-get remove --purge man-db -yq

          # Add LLVM apt signing key
          wget -qO- https://apt.llvm.org/llvm-snapshot.gpg.key \
            | sudo tee /etc/apt/trusted.gpg.d/apt.llvm.org.asc

          # Add LLVM apt repo
          RELEASE_NAME=$(lsb_release -sc 2>/dev/null || echo "noble")
          echo "deb https://apt.llvm.org/${RELEASE_NAME}/ llvm-toolchain-${RELEASE_NAME}-${CLANG_VERSION} main" \
            | sudo tee /etc/apt/sources.list.d/llvm.list

          sudo apt-get update -yq
          sudo apt-get install -yq "clang-format-${CLANG_VERSION}"

      - name: Run clang-format check (src)
        env:
          CLANG_FORMAT: clang-format-${{ inputs.clang-version || '18' }}
        working-directory: ${{ github.workspace }}
        run: ./scripts/clang-format-check.sh src .

      - name: Run clang-format check (include)
        env:
          CLANG_FORMAT: clang-format-${{ inputs.clang-version || '18' }}
        working-directory: ${{ github.workspace }}
        run: ./scripts/clang-format-check.sh include .

      - name: Run clang-format check (examples)
        env:
          CLANG_FORMAT: clang-format-${{ inputs.clang-version || '18' }}
        working-directory: ${{ github.workspace }}
        run: ./scripts/clang-format-check.sh examples .

      - name: Show results
        if: always()
        run: |
          [ -f clang-format-results.txt ] && cat clang-format-results.txt || true

      - name: Publish Report
        if: always()
        uses: actions/upload-artifact@65c4c4a1ddee5b72f698fdd19549f0f0fb45cf08 # v4.6.1
        with:
          name: clang-format-results
          path: clang-format-*